# Generated by Django 6.0.7 on 2026-07-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.CharField(max_length=32)),
                ('retail_price', models.DecimalField(decimal_places=8, max_digits=11)),
                ('geocode_status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed'), ('out_of_scope', 'Out of scope')], default='pending', max_length=16)),
                ('geocode_precision', models.CharField(blank=True, choices=[('rooftop', 'Rooftop'), ('city', 'City centroid')], max_length=16, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('observation_count', models.PositiveIntegerField(default=1)),
                ('price_min', models.DecimalField(decimal_places=8, max_digits=11)),
                ('price_max', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='routing_sta_latitud_bb43d5_idx')],
            },
        ),
    ]
