# Generated by Django 6.0.7 on 2026-08-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='price_source',
            field=models.CharField(choices=[('opis_indexed', 'OPIS indexed'), ('eia_regional_estimate', 'EIA regional estimate')], default='opis_indexed', max_length=32),
        ),
    ]
