# Generated by Django 6.0.7 on 2026-08-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_station_price_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='gers_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='source',
            field=models.CharField(choices=[('opis', 'OPIS'), ('overture', 'Overture')], default='opis', max_length=16),
        ),
    ]
